language: cpp
sudo: required
os: linux
dist: xenial
service:
- docker
env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_DIST=sagemath/sagemath
  - MY_MODE="sagemath"
  - MY_TARGET_MOUNT=/tell/note-on-subgroup-security
before_install:
- env
- docker pull $MY_TARGET_DIST
script:
- make SAGE="docker run -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -it $MY_TARGET_DIST cd $MY_TARGET_MOUNT; sage"
# after_failure:
# - tail -n 1000 make.log
notifications:
  on_success: change
  on_failure: always
# vim: set expandtab shiftwidth=2 softtabstop=2 :
