language: cpp
os: linux
dist: xenial
services:
- docker
env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_DIST=sagemath/sagemath:8.9
  - MY_MODE="sagemath"
  - MY_TARGET_MOUNT=/tell/note-on-subgroup-security
before_install:
- env | sort
- docker pull $MY_TARGET_DIST
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -td $MY_TARGET_DIST /bin/bash
- docker exec -ti $MY_NAME bash -c "sudo apt update" > /dev/null
install:
- docker exec -ti $MY_NAME bash -c "sudo apt install -y make" > /dev/null
script:
- docker exec -ti $MY_NAME bash -c "sage -c 'print(f\"SageMath version {sage.version.version}\")'"
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT; sudo make"
# after_failure:
# - tail -n 1000 make.log
notifications:
  on_success: change
  on_failure: always
# vim: set expandtab shiftwidth=2 softtabstop=2 :
