language: cpp
sudo: required
os: linux
dist: xenial
service:
- docker
env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_DIST=sagemath/sagemath
  - MY_MODE="sagemath"
  - MY_TARGET_MOUNT=/tell/note-on-subgroup-security
before_install:
- env
- docker pull $MY_TARGET_DIST
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -td $MY_TARGET_DIST /bin/bash
- docker exec -ti $MY_NAME bash -c "apt update" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y build-essential" > /dev/null
script:
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT; make"
# after_failure:
# - tail -n 1000 make.log
notifications:
  on_success: change
  on_failure: always
# vim: set expandtab shiftwidth=2 softtabstop=2 :
